BCM: int
BOARD: int
OUT: int
IN: int
LOW: int
HIGH: int

def setmode(mode: int) -> None: ...
def setup(channel: int, direction: int) -> None: ...
def output(channel: int, value: int) -> None: ...
def cleanup() -> None: ...
