from typing import Any

import numpy as np

class Picamera2:
    def create_still_configuration(
        self,
        main: dict[str, Any] | None = None,
    ) -> dict[str, Any]: ...
    def configure(self, config: dict[str, Any]) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def capture_array(self) -> np.ndarray: ...
